.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tlslb 1  "tlslb 0.1.0" 
.SH NAME
tlslb \- A TCP/TLS loadbalancer
.SH SYNOPSIS
\fBtlslb\fR <\fB\-c\fR|\fB\-\-config\-file\fR> [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
A TCP/TLS loadbalancer
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\-file\fR=\fICONFIG_FILE\fR
Path to the config file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
